
update_fastlane

default_platform(:ios)

platform :ios do
 
  fastlane_require 'cocoapods'

  before_all do
    ensure_git_branch(
        branch: 'master'
      )
      ensure_git_status_clean
      cocoapods
      match
      build_number = number_of_commits(all: true)
  end


  desc "Bumps the patch version"  
  lane :patch do
      update(type: "patch")
  end

  desc "Bumps the minor version"  
  lane :minor do
      update(type: "minor")
  end  

  desc "Bumps the major version"  
  lane :major do
      update(type: "major")
  end  	

  private_lane :update do |options|

    type = options[:type]
	    
    increment_version_number(
      bump_type: type 
    )
    
    build_app(workspace: "OpenCamera.xcworkspace", scheme: "OpenCamera")
    
    upload_to_testflight(
      skip_submission: true
    )
    
    commit_version_bump(
            message: "Version Bump",# create a commit with a custom message
            xcodeproj: $project
          )

    add_git_tag(tag: "testflight-#{build_number}")

    push_to_git_remote()

    end
end
